#! /usr/bin/env python
# -*- coding: utf-8 -*-

"""Automatic Docker Deployment via Webhooks"""

from os import system
from argparse import ArgumentParser, ArgumentDefaultsHelpFormatter
from BaseHTTPServer import BaseHTTPRequestHandler, HTTPServer

ADDR = "0.0.0.0"
PORT = 8555

parser = ArgumentParser(description=__doc__,
                        formatter_class=ArgumentDefaultsHelpFormatter)

parser.add_argument("-t", "--token",
                    dest="token",
                    required=True,
                    help=("Secure auth token (can be choosen "
                          "arbitrarily)"))
parser.add_argument("-c", "--cmd",
                    dest="cmd",
                    required=True,
                    nargs="*",
                    help="Command to execute when triggered")

args = parser.parse_args()


class RequestHandler(BaseHTTPRequestHandler):
    def do_POST(self):
        print(self.path)
        if args.token in self.path:
            system(" ".join(args.cmd))
            self.send_response(200, "OK")
        else:
            self.send_response(401, "Not authorized")
        self.end_headers()

httpd = HTTPServer((ADDR, PORT), RequestHandler)
httpd.serve_forever()
